# Generated by Django 5.2.1 on 2025-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=7),
        ),
    ]
