# Generated by Django 5.2.1 on 2025-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_cover_store_logo_store_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='font',
            field=models.CharField(blank=True, default='Cairo', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='layout',
            field=models.CharField(choices=[('grid', 'شبكة'), ('list', 'قائمة')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(blank=True, default='#FCBA7E', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='welcome_message',
            field=models.CharField(blank=True, default='مرحبًا بكم في متجري!', max_length=255),
        ),
    ]
