# Generated by Django 5.2.1 on 2025-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_font_store_layout_store_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='store',
            name='card_shape',
            field=models.CharField(choices=[('rounded', 'دائري'), ('square', 'مربع')], default='rounded', max_length=10),
        ),
    ]
