# Generated by Django 5.2.1 on 2025-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_banner_image_store_card_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='banner_image',
        ),
    ]
